# -*- mode: ruby -*-
# vi:set ft=ruby :

Vagrant.configure("2") do |config|
   config.vm.box = "rockylinux/9"
   config.vm.box_version = "4.0.0"
   config.vm.network "private_network", ip: "192.168.1.10"
   config.vm.network "forwarded_port", guest: 8080, host: 8080
   config.vm.network "forwarded_port", guest:50000, host: 50000
   config.vm.provision "ansible" do |ansible|
     ansible.playbook = "playbook.yml"
   end
   config.vm.provider "virtualbox" do |vb|
   vb.memory = "2048"
   end
end
